# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
        stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.1'
    hooks:
    -   id: flake8
        stages: [commit]
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: .venv/bin/pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]